name: Deploy YI to Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 配置 GitHub Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true

      - name: 上传静态资源
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/yi

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: 发布到 GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
